package:
  name: fitsio
  version: "{{version}}"

source:
  fn: fitsio-{{version}}.tar.gz
  url: https://pypi.io/packages/source/f/fitsio/fitsio-{{version}}.tar.gz
  md5: {{md5}}

# build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - numpy

  run:
    - python
    - numpy

test:
  imports:
    - fitsio

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/esheldon/fitsio
  license: GNU General Public License (GPL)
  summary: 'A full featured python library to read from and write to FITS files.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
